/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NFS_constants.h"



const NFSConstants g_NFS_constants;

NFSConstants::NFSConstants() {
}



