/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NFS_CONSTANTS_H
#define NFS_CONSTANTS_H

#include "NFS_types.h"



class NFSConstants {
 public:
  NFSConstants();

};

extern const NFSConstants g_NFS_constants;



#endif
